// Offline Quran data will be loaded here
// This file will be generated by downloading from API
const QURAN_OFFLINE = {};

// Function to save downloaded data
function saveQuranData(surahId, verses) {
    QURAN_OFFLINE[surahId] = verses;
    localStorage.setItem('quran_offline_' + surahId, JSON.stringify(verses));
}

// Function to load from localStorage
function loadQuranData(surahId) {
    const cached = localStorage.getItem('quran_offline_' + surahId);
    return cached ? JSON.parse(cached) : null;
}

// Function to check if all data is downloaded
function isFullyOffline() {
    for (let i = 1; i <= 114; i++) {
        if (!localStorage.getItem('quran_offline_' + i)) {
            return false;
        }
    }
    return true;
}
